using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Countries.UI
{
    /// <summary>
    /// This helper contains the JSon input string and the deserialization to a dynamic object
    /// </summary>
    static class JSonHelper
    {
        /// <summary>
        /// Deserialize the JSon input to an object
        /// </summary>
        /// <returns></returns>
        public static dynamic GetJsonObject()
        {
            return System.Web.Helpers.Json.Decode(GetJSonInput());
        }

        /// <summary>
        /// Returns a string containing the initial data in json format
        /// </summary>
        /// <returns></returns>
        static string GetJSonInput()
        {
            return @"
                [
                  {
                    ""Name"":""Afghanistan"",
                    ""Population"":25500100,
                    ""GDP"":20364,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Albania"",
                    ""Population"":2895947,
                    ""GDP"":12044,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Andorra"",
                    ""Population"":76098,
                    ""GDP"":3222,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Angola"",
                    ""Population"":19183590,
                    ""GDP"":116308,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Antigua and Barbuda"",
                    ""Population"":86295,
                    ""GDP"":1176,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Argentina"",
                    ""Population"":42669500,
                    ""GDP"":477028,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Armenia"",
                    ""Population"":3017400,
                    ""GDP"":995,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Australia"",
                    ""Population"":23555600,
                    ""GDP"":1564419,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Austria"",
                    ""Population"":8504850,
                    ""GDP"":394458,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Azerbaijan"",
                    ""Population"":9477100,
                    ""GDP"":68727,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Bahamas"",
                    ""Population"":351461,
                    ""GDP"":8043,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Bahrain"",
                    ""Population"":1234571,
                    ""GDP"":30362,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Bangladesh"",
                    ""Population"":156608000,
                    ""GDP"":127195,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Barbados"",
                    ""Population"":285,
                    ""GDP"":4533,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Belarus"",
                    ""Population"":9467000,
                    ""GDP"":63259,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Belgium"",
                    ""Population"":11198638,
                    ""GDP"":483402,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Belize"",
                    ""Population"":349728,
                    ""GDP"":1554,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Benin"",
                    ""Population"":9988068,
                    ""GDP"":7557,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Bhutan"",
                    ""Population"":74941,
                    ""GDP"":1861,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Bolivia"",
                    ""Population"":10027254,
                    ""GDP"":27035,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Bosnia and Herzegovina"",
                    ""Population"":3791622,
                    ""GDP"":17319,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Botswana"",
                    ""Population"":2024904,
                    ""GDP"":1441,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Brazil"",
                    ""Population"":202838000,
                    ""GDP"":2254109,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Brunei"",
                    ""Population"":393162,
                    ""GDP"":16954,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Bulgaria"",
                    ""Population"":7245677,
                    ""GDP"":50972,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Burkina Faso"",
                    ""Population"":17322796,
                    ""GDP"":10687,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Burundi"",
                    ""Population"":9420248,
                    ""GDP"":2257,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Cambodia"",
                    ""Population"":15184116,
                    ""GDP"":14038,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Cameroon"",
                    ""Population"":20386799,
                    ""GDP"":26094,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Canada"",
                    ""Population"":35427524,
                    ""GDP"":1821445,
                    ""Continent"":""Asia""
                  },
                  {
                    ""Name"":""Cape Verde"",
                    ""Population"":491875,
                    ""GDP"":1903,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Central African Republic"",
                    ""Population"":4709000,
                    ""GDP"":2184,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Chad"",
                    ""Population"":13211000,
                    ""GDP"":10183,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Chile"",
                    ""Population"":17773000,
                    ""GDP"":268314,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""China[8]"",
                    ""Population"":1365530000,
                    ""GDP"":8358400,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Colombia"",
                    ""Population"":47675000,
                    ""GDP"":369813,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Comoros"",
                    ""Population"":743798,
                    ""GDP"":616,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Costa Rica"",
                    ""Population"":4667096,
                    ""GDP"":45107,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Croatia"",
                    ""Population"":4290612,
                    ""GDP"":56447,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Cuba"",
                    ""Population"":11167325,
                    ""GDP"":71017,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Cyprus[20]"",
                    ""Population"":865878,
                    ""GDP"":22768,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Czech Republic"",
                    ""Population"":10517400,
                    ""GDP"":196446,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Denmark"",
                    ""Population"":5634437,
                    ""GDP"":314889,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Djibouti"",
                    ""Population"":886,
                    ""GDP"":1361,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Dominica"",
                    ""Population"":71293,
                    ""GDP"":499,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Dominican Republic"",
                    ""Population"":9445281,
                    ""GDP"":58898,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Ecuador"",
                    ""Population"":15780500,
                    ""GDP"":87495,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Egypt"",
                    ""Population"":86787400,
                    ""GDP"":254671,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""El Salvador"",
                    ""Population"":6384000,
                    ""GDP"":23864,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Equatorial Guinea"",
                    ""Population"":1622000,
                    ""GDP"":14491,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Eritrea"",
                    ""Population"":6536000,
                    ""GDP"":3108,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Estonia"",
                    ""Population"":1315819,
                    ""GDP"":22376,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Ethiopia"",
                    ""Population"":87952991,
                    ""GDP"":41605,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Fiji"",
                    ""Population"":858038,
                    ""GDP"":3999,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Finland"",
                    ""Population"":5458038,
                    ""GDP"":247389,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""France[10]"",
                    ""Population"":65931000,
                    ""GDP"":2611221,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Gabon"",
                    ""Population"":1711000,
                    ""GDP"":24076,
                    ""Continent"":""Europe""
                  },
                  {
                    ""Name"":""Gambia"",
                    ""Population"":1882450,
                    ""GDP"":917,
                    ""Continent"":""Oceania""
                  },
                  {
                    ""Name"":""Georgia[16]"",
                    ""Population"":4490500,
                    ""GDP"":1583,
                    ""Continent"":""Oceania""
                  },
                  {
                    ""Name"":""Germany"",
                    ""Population"":80716000,
                    ""GDP"":3425956,
                    ""Continent"":""Oceania""
                  },
                  {
                    ""Name"":""Ghana"",
                    ""Population"":27043093,
                    ""GDP"":40711,
                    ""Continent"":""Oceania""
                  },
                  {
                    ""Name"":""Greece"",
                    ""Population"":11123034,
                    ""GDP"":248941,
                    ""Continent"":""Oceania""
                  },
                  {
                    ""Name"":""Grenada"",
                    ""Population"":103328,
                    ""GDP"":783,
                    ""Continent"":""Oceania""
                  },
                  {
                    ""Name"":""Guatemala"",
                    ""Population"":15806675,
                    ""GDP"":50377,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Guinea"",
                    ""Population"":10628972,
                    ""GDP"":6092,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Guinea-Bissau"",
                    ""Population"":1746000,
                    ""GDP"":849,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Guyana"",
                    ""Population"":784894,
                    ""GDP"":2851,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Haiti"",
                    ""Population"":10413211,
                    ""GDP"":7187,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Honduras"",
                    ""Population"":8555072,
                    ""GDP"":18564,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Hungary"",
                    ""Population"":9879000,
                    ""GDP"":1246,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Iceland"",
                    ""Population"":32634,
                    ""GDP"":13579,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""India"",
                    ""Population"":1246540000,
                    ""GDP"":1875213,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Indonesia"",
                    ""Population"":252164800,
                    ""GDP"":878043,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Iran"",
                    ""Population"":77574000,
                    ""GDP"":551588,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Iraq"",
                    ""Population"":36004552,
                    ""GDP"":14937,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Ireland"",
                    ""Population"":4593100,
                    ""GDP"":210638,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Israel"",
                    ""Population"":8193900,
                    ""GDP"":241069,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Italy"",
                    ""Population"":60782668,
                    ""GDP"":2013392,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Jamaica"",
                    ""Population"":2717991,
                    ""GDP"":14795,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Japan"",
                    ""Population"":127090000,
                    ""GDP"":5960180,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Jordan"",
                    ""Population"":6605660,
                    ""GDP"":30937,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Kazakhstan"",
                    ""Population"":17244000,
                    ""GDP"":202656,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Kenya"",
                    ""Population"":45546000,
                    ""GDP"":40697,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Kiribati"",
                    ""Population"":106461,
                    ""GDP"":176,
                    ""Continent"":""America""
                  },
                  {
                    ""Name"":""Kuwait"",
                    ""Population"":3065850,
                    ""GDP"":183219,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Kyrgyzstan"",
                    ""Population"":5776570,
                    ""GDP"":6475,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Laos"",
                    ""Population"":6580800,
                    ""GDP"":91,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Latvia"",
                    ""Population"":1996500,
                    ""GDP"":28379,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Lebanon"",
                    ""Population"":4966000,
                    ""GDP"":4249,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Lesotho"",
                    ""Population"":2098000,
                    ""GDP"":2443,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Liberia"",
                    ""Population"":4397000,
                    ""GDP"":1491,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Libya"",
                    ""Population"":6253000,
                    ""GDP"":95802,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Liechtenstein"",
                    ""Population"":37132,
                    ""GDP"":5827,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Lithuania"",
                    ""Population"":2939431,
                    ""GDP"":42339,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Luxembourg"",
                    ""Population"":5497,
                    ""GDP"":55143,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Madagascar"",
                    ""Population"":21263403,
                    ""GDP"":9968,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Malawi"",
                    ""Population"":16829000,
                    ""GDP"":5653,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Malaysia"",
                    ""Population"":30188000,
                    ""GDP"":304726,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Maldives"",
                    ""Population"":31728,
                    ""GDP"":2606,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Mali"",
                    ""Population"":15768000,
                    ""GDP"":10262,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Malta"",
                    ""Population"":416055,
                    ""GDP"":8775,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Marshall Islands"",
                    ""Population"":56086,
                    ""GDP"":198,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Mauritania"",
                    ""Population"":3461041,
                    ""GDP"":3866,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Mauritius"",
                    ""Population"":1257900,
                    ""GDP"":11452,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Mexico"",
                    ""Population"":119713203,
                    ""GDP"":1183655,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Moldova[18]"",
                    ""Population"":3557600,
                    ""GDP"":7253,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Monaco"",
                    ""Population"":3695,
                    ""GDP"":5707,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Mongolia"",
                    ""Population"":2931300,
                    ""GDP"":10271,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Montenegro"",
                    ""Population"":620029,
                    ""GDP"":4046,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Morocco"",
                    ""Population"":33316200,
                    ""GDP"":95992,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Mozambique"",
                    ""Population"":23700715,
                    ""GDP"":14605,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Namibia"",
                    ""Population"":2113077,
                    ""GDP"":12807,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Nauru"",
                    ""Population"":9945,
                    ""GDP"":121,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Nepal"",
                    ""Population"":26494504,
                    ""GDP"":18029,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Netherlands"",
                    ""Population"":16858800,
                    ""GDP"":800535,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""New Zealand"",
                    ""Population"":4540210,
                    ""GDP"":171256,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Nicaragua"",
                    ""Population"":6071045,
                    ""GDP"":10508,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Niger"",
                    ""Population"":17138707,
                    ""GDP"":6773,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Nigeria"",
                    ""Population"":178517000,
                    ""GDP"":28647,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""North Korea"",
                    ""Population"":25027000,
                    ""GDP"":14411,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Norway"",
                    ""Population"":5124383,
                    ""GDP"":499667,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Oman"",
                    ""Population"":4020000,
                    ""GDP"":78111,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Pakistan"",
                    ""Population"":188020000,
                    ""GDP"":215117,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Palau"",
                    ""Population"":20901,
                    ""GDP"":213,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Panama"",
                    ""Population"":3405813,
                    ""GDP"":36253,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Papua New Guinea"",
                    ""Population"":7398500,
                    ""GDP"":15677,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Paraguay"",
                    ""Population"":6783374,
                    ""GDP"":25935,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Peru"",
                    ""Population"":30814175,
                    ""GDP"":204681,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Philippines"",
                    ""Population"":99848300,
                    ""GDP"":250182,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Poland"",
                    ""Population"":38496000,
                    ""GDP"":489852,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Portugal"",
                    ""Population"":10477800,
                    ""GDP"":212139,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Qatar"",
                    ""Population"":2174035,
                    ""GDP"":192402,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Romania"",
                    ""Population"":19942642,
                    ""GDP"":169396,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Russia[9]"",
                    ""Population"":146048500,
                    ""GDP"":2029812,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Rwanda"",
                    ""Population"":10537222,
                    ""GDP"":7103,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Samoa"",
                    ""Population"":18782,
                    ""GDP"":681,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""San Marino"",
                    ""Population"":33664,
                    ""GDP"":1853,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""S?o Tom? and Pr?ncipe"",
                    ""Population"":187356,
                    ""GDP"":261,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Saudi Arabia"",
                    ""Population"":29994272,
                    ""GDP"":71105,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Senegal"",
                    ""Population"":12873601,
                    ""GDP"":13962,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Serbia[15]"",
                    ""Population"":7146759,
                    ""GDP"":38491,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Seychelles"",
                    ""Population"":90945,
                    ""GDP"":1031,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Sierra Leone"",
                    ""Population"":6190280,
                    ""GDP"":43366,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Singapore"",
                    ""Population"":5399200,
                    ""GDP"":27652,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Slovakia"",
                    ""Population"":5415949,
                    ""GDP"":91349,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Slovenia"",
                    ""Population"":2063250,
                    ""GDP"":4538,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Solomon Islands"",
                    ""Population"":581344,
                    ""GDP"":101,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Somalia[14]"",
                    ""Population"":10806000,
                    ""GDP"":1306,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""South Africa"",
                    ""Population"":52981991,
                    ""GDP"":384313,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""South Korea"",
                    ""Population"":50423955,
                    ""GDP"":1129598,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""South Sudan"",
                    ""Population"":11739000,
                    ""GDP"":1006,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Spain"",
                    ""Population"":46609700,
                    ""GDP"":1322126,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Sri Lanka"",
                    ""Population"":20277597,
                    ""GDP"":59421,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Sudan"",
                    ""Population"":37289406,
                    ""GDP"":51453,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Suriname"",
                    ""Population"":534189,
                    ""GDP"":5012,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Swaziland"",
                    ""Population"":1268000,
                    ""GDP"":3861,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Sweden"",
                    ""Population"":9684858,
                    ""GDP"":523804,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Switzerland"",
                    ""Population"":8160900,
                    ""GDP"":631183,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Syria"",
                    ""Population"":21987000,
                    ""GDP"":4654,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Tajikistan"",
                    ""Population"":8160000,
                    ""GDP"":7633,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Tanzania"",
                    ""Population"":44928923,
                    ""GDP"":28249,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Thailand"",
                    ""Population"":64456700,
                    ""GDP"":385694,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Timor-Leste"",
                    ""Population"":1212107,
                    ""GDP"":5387,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Togo"",
                    ""Population"":6993000,
                    ""GDP"":3917,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Tonga"",
                    ""Population"":103036,
                    ""GDP"":465,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Trinidad and Tobago"",
                    ""Population"":1328019,
                    ""GDP"":23225,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Tunisia"",
                    ""Population"":10886500,
                    ""GDP"":45132,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Turkey"",
                    ""Population"":76667864,
                    ""GDP"":788299,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Turkmenistan"",
                    ""Population"":5307000,
                    ""GDP"":33466,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Tuvalu"",
                    ""Population"":11323,
                    ""GDP"":40,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Uganda"",
                    ""Population"":35357000,
                    ""GDP"":21736,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Ukraine[11]"",
                    ""Population"":42839621,
                    ""GDP"":176309,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""United Arab Emirates"",
                    ""Population"":9446000,
                    ""GDP"":383799,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""United Kingdom"",
                    ""Population"":64105700,
                    ""GDP"":2471600,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""United States"",
                    ""Population"":318372000,
                    ""GDP"":16244600,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Uruguay"",
                    ""Population"":3286314,
                    ""GDP"":49919,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Uzbekistan"",
                    ""Population"":30492800,
                    ""GDP"":51414,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Vanuatu"",
                    ""Population"":264652,
                    ""GDP"":752,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Venezuela"",
                    ""Population"":28946101,
                    ""GDP"":382424,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Vietnam"",
                    ""Population"":89708900,
                    ""GDP"":15582,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Yemen"",
                    ""Population"":25235000,
                    ""GDP"":32831,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Zambia"",
                    ""Population"":15023315,
                    ""GDP"":2149,
                    ""Continent"":""Africa""
                  },
                  {
                    ""Name"":""Zimbabwe"",
                    ""Population"":13061239,
                    ""GDP"":9802,
                    ""Continent"":""Africa""
                  }
                ]";

        }


    }
}
